# Generated by Django 2.2.3 on 2019-11-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=20)),
                ('Descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
    ]
